app = "squidbox-api"
primary_region = "fra"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

[checks.health]
  type = "http"
  interval = "10s"
  timeout = "2s"
  method = "get"
  path = "/health"

[[processes]]
  command = ["node", "dist/api-main.js"]
